ci:
  # Attempts to use networking and fails at name resolution
  skip: [bundler-audit]
  # Forĝejo/Gitea mirrors will autoclose pull requests. This should decrease
  # the frequency of unnecessary PRs.
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quaterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        # Let's not touch LICENSE files or reuse.software directory
        exclude: ^LICENSES\/.*|LICENSE$
        # File types depending on trailing whitespace. Use identify-cli
        exclude_types: [tsv, markdown]

  # Markdown Table of Contents generation.
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        # https://github.com/Mikaela/gist/blob/master/doctoc.txt
        args: [--update-only]

  # GitHub Actions etc. configuration validity checking
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-gitlab-ci

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: bundler-audit
      # https://github.com/jumanjihouse/pre-commit-hooks/issues/111
      #- id: check-mailmap

  # Easierish licensing when attempting reuse compliancy
  #- repo: https://github.com/fsfe/reuse-tool
  #  rev: v1.1.2
  #  hooks:
  #    - id: reuse

  # prettier & editorconfig checker should probably be ran last

  # prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier

  # .editorconfig validity checking
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
        # I don't actually care about line lengths as more than a guideline
        args: [-disable-max-line-length]
