# Remember to run `pre-commit install` at least once!
# Manual test run: `pre-commit run --all-files`
# Update? `pre-commit autoupdate`
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
