#!/usr/bin/env bash
# Do not use this script unless you know what you are doing!
cat bashrc > ~/.bashrc
cat tmux.conf > ~/.tmux.conf
cat zshrc > ~/.zshrc
cat gitconfig > ~/.gitconfig
cat vimrc > ~/.vimrc
mkdir -p ~/.gnupg
cat gpg.conf > ~/.gnupg/gpg.conf
cat xsessionrc > ~/.xsessionrc
cat pastebinit.xml > ~/.pastebinit.xml
gpg --quiet --import .keys/0x4DB53CFE82A46728.asc&
mkdir -p ~/.ssh
chmod 700 ~/.ssh --recursive
chmod 700 ~/.gnupg --recursive
# vim : set ft=sh :
