#!/usr/bin/env bash
# Do not use this script unless you know what you are doing!
set -x

if [ -d ~/src/gitea.blesmrt.net/Mikaela/ssh-allowed_signers ]; then
	git verify-commit HEAD
	sleep 3
else
	echo "Keys not found, cloning..."
	mkdir -vp ~/src/gitea.blesmrt.net/Mikaela/
	git clone https://gitea.blesmrt.net/Mikaela/ssh-allowed_signers.git ~/src/gitea.blesmrt.net/Mikaela/ssh-allowed_signers
fi

export MIKAELA_GREP=$HOME/.MIKAELA_GREP

cat rc/bashrc > ~/.bashrc
cat conf/tmux.conf > ~/.tmux.conf
cat rc/zshrc > ~/.zshrc
cat rc/profile > ~/.profile
mkdir -vp ~/.config/git
cat conf/gitconfig > ~/.config/git/config
touch ~/.gitconfig
rm ~/.gitconfig
ln -nsfv ~/.config/git/config ~/.gitconfig
mkdir -vp ~/.git-template
cat rc/vimrc > ~/.vimrc
mkdir -vp ~/.config/nvim/
cat conf/init.vim > ~/.config/nvim/init.vim
cat conf/makepkg.conf > ~/.makepkg.conf
mkdir -vp ~/.config/mpv/
cat conf/mpv.conf > ~/.config/mpv/mpv.conf
if [ ! -f ~/.oidentd.conf ]; then
	cat conf/oidentd.conf > ~/.oidentd.conf
fi
mkdir -vp ~/.gnupg
cat gpg/gpg.conf > ~/.gnupg/gpg.conf
cat gpg/gpg-agent.conf > ~/.gnupg/gpg-agent.conf
cat gpg/dirmngr.conf > ~/.gnupg/dirmngr.conf
killall -HUP dirmngr
#cat rc/xinitrc > ~/.xinitrc
cat conf/pastebinit.xml > ~/.pastebinit.xml
cat conf/Xresources > ~/.Xresources
mkdir -vp ~/.inxi
cat conf/inxi.conf > ~/.inxi/inxi.conf
gpg --quiet --import .mikaela/keys/*.asc &
mkdir -vp ~/.ssh/sockets/
mkdir -vp ~/.local/bin/
chmod a+xr chmod
bash -x ./chmod &
git submodule update --init &

if hash pre-commit 2> /dev/null; then
	pre-commit init-templatedir ~/.git-template
	pre-commit gc
fi

if hash corepack 2> /dev/null; then
	corepack enable --install-directory ~/.local/bin/
	corepack enable npm --install-directory ~/.local/bin/
else
	echo "WARNING! corepack is not installed."
fi

if [ "$(id -u)" == "0" ]; then
	mkdir -vp /etc/apt/apt.conf.d/
	echo 'Dpkg::Progress-Fancy "1";' > /etc/apt/apt.conf.d/99progressbar
	echo 'APT::Color "1";' > /etc/apt/apt.conf.d/99color
	if hash updatedb 2> /dev/null; then
		(updatedb &)
	fi
fi

if [ -f "$MIKAELA_GREP" ]; then
	bash -x .mikaela_install
fi

(git lfs install | true &)

set +x
# vim : set ft=sh :
#chmod 700 $HOME -R
