# Brownie points for no data transmitted outside of the EU and thus
# GDPR-compatible
[Resolve]
DNS=
DNS=2a0f:fc80::#dns0.eu 2a0f:fc81::#dns0.eu
DNS=193.110.81.0#dns0.eu 185.253.5.0#dns0.eu
DNS=2a13:1001::86:54:11:1#protective.joindns4.eu
DNS=86.54.11.1#protective.joindns4.eu
FallbackDNS=
Domains=~.
DNSSEC=true
DNSOverTLS=true
Cache=true
# vim: filetype=systemd
