# 99-working-dns.conf
[Resolve]
DNS=
DNS=::1
DNS=127.0.0.1
DNS=2a0f:fc80::#dns0.eu 2a0f:fc81::#dns0.eu
DNS=193.110.81.0#dns0.eu 185.253.5.0#dns0.eu
DNS=2620:fe::11#dns11.quad9.net 2620:fe::fe:11#dns11.quad9.net [2620:fe::11]:8853#dns11.quad9.net [2620:fe::fe:11]:8853#dns11.quad9.net
DNS=149.112.112.11#dns11.quad9.net 9.9.9.11#dns11.quad9.net 149.112.112.11:8853#dns11.quad9.net 9.9.9.11:8853#dns11.quad9.net
FallbackDNS=
FallbackDNS=::1
FallbackDNS=127.0.0.1
Domains=~.
# I lied. https://github.com/systemd/systemd/issues/34896 https://github.com/systemd/systemd/issues/35126
DNSSEC=true
DNSOverTLS=opportunistic
Cache=true
# vim: filetype=systemd
