# 99-working-dns.conf
[Resolve]
DNS=
DNS=::1
DNS=127.0.0.1
DNS=2a0f:fc80::#dns0.eu 2a0f:fc81::#dns0.eu
DNS=193.110.81.0#dns0.eu 185.253.5.0#dns0.eu
DNS=2620:fe::fe:853#dns.quad9.net 2620:fe::9:853#dns.quad9.net 2620:fe::fe:8853#dns.quad9.net 2620:fe::9:8853#dns.quad9.net
DNS=9.9.9.9:853 149#dns.quad9.net.112.112.112:853#dns.quad9.net 9.9.9.9:8853#dns.quad9.net 149.112.112.112:8853#dns.quad9.net
DNS=2a13:1001::86:54:11:1#protective.joindns4.eu
DNS=86.54.11.1#protective.joindns4.eu
FallbackDNS=
FallbackDNS=::1
FallbackDNS=127.0.0.1
Domains=~.
# I lied. https://github.com/systemd/systemd/issues/34896 https://github.com/systemd/systemd/issues/35126
DNSSEC=true
DNSOverTLS=opportunistic
Cache=true
# vim: filetype=systemd
