#!/usr/bin/env bash
# FOR MY PERSONAL USE ONLY!

mkdir -p /etc/
cat oidentd.conf >/etc/oidentd.conf
chmod a+r /etc/oidentd.conf

mkdir -p /etc/profile.d/
cat profile.d/mikaela.sh >/etc/profile.d/mikaela.sh
chmod a+r /etc/profile.d/mikaela.sh

mkdir -p /etc/systemd/system/
cat systemd/system/oidentd.socket >/etc/systemd/system/oidentd.socket
chmod a+r /etc/systemd/system/oidentd.socket

mkdir -p /etc/sysctl.d/
if [ ! -f /etc/sysctl.d/60-mikaela.conf ]; then
	cat sysctl.d/60-mikaela.conf >/etc/sysctl.d/60-mikaela.conf
	chmod a+r /etc/sysctl.d/60-mikaela.conf
fi

echo 'If you use systemd or oidentd you should "systemctl daemon-reload"'
echo 'and "systemctl restart oidentd".'
echo 'You should also "sysctl --system -p".'
