# $(bat --config-file)

# Enable this to use italic text on the terminal.
--italic-text=always
# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
--pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#	Use ".gitignore"-style highlighting for ".*ignore" files
--map-syntax ".*ignore:Git Ignore"
