# ~/.MangoHud/$APPNAME.conf
# MangoHud.conf in binary directory
# ~/.MangoHud/MangoHud.conf

# 16 is comfortable on a smaller TV, 20 on a laptop on lap, 32 on a more
# modern TV
#font_size=16
font_size=20
#font_size=32
font_file=~/.shell-things/submodules/atkinson-hyperlegible-next-mono/fonts/variable/AtkinsonHyperlegibleMono[wght].ttf

# Other settings than font
background_alpha=0
battery_time
battery
blacklist=
cpu_stats
cpu_temp
device_battery=gamepad+mouse
device_battery_icon
display_server
fan
fps
frametime
frame_timing
gpu_stats
gpu_temp
horizontal
mangoapp_steam
position=bottom-left
ram
read_cfg
swap
text_outline
throttling_status
time
time_format=%X
time_no_label
vram
wine
