# ~/.MangoHud/$APPNAME.conf
# MangoHud.conf in binary directory
# ~/.MangoHud/MangoHud.conf
background_alpha=0
battery_time
battery
blacklist=
cpu_stats
cpu_temp
device_battery=gamepad+mouse
device_battery_icon
display_server
fan
font_size=13
fps
frametime
frame_timing
gpu_stats
gpu_temp
horizontal
mangoapp_steam
no_small_font
position=bottom-left
ram
read_cfg
retro
swap
text_outline
throttling_status
time
time_format=%X
time_no_label
vram
wine
