# <~/.config/mpv/mpv.conf|~/.var/app/io.mpv.Mpv/config/mpv/mpv.conf>

# Preferred audio drivers, but by trailing comma, let others be used too.
ao=pipewire,pulse,
# And same for video output drivers
vo=gpu-next,gpu,

# Compatible options that apparently use vulkan for mangohud on my hardware
# anyway \o/
profile=fast
hwdec=auto
gpu-api=auto
gpu-context=auto

# Resolve audio/video descynchronisation automatically by adjusting audio
# speed
video-sync=display-resample
interpolation

# Specify preferred audio and subtitle languages. Two subtitles are shown
# simultaneously, one on top, another on bottom.
# REMEMBER to override this with --alang= --slang= as needed!
alang=jpn,jp,ja,en,eng,fi,fin
slang=fi,fin,sdh,doh,en,eng,eo,epo,la,lat,sv,swe,ru,rus,cs,ces,cze,es,spa,jpn,jp

# Remember quit position even without Shift+Q
save-position-on-quit

# Disable embedded fonts in subtitle files and use my preferred font for both
# subtitles and UI. Subtitle preferred font may get used if it exists in the
# system though?
embeddedfonts=no
sub-font='Inclusive Sans'
osd-font='Inclusive Sans'

# Amber font color for subtitles, unless they otherwise specify?
sub-color='#ffb700'

# Enable two simultaneous subtitles (first slang on bottom, second on top?)
sid=auto
secondary-sid=auto

# Explicitly disable SDH/HOH element hiding from subs, these are defaults
sub-filter-sdh=no
sub-filter-sdh-harder=no

# Try to detect subtitle files even if not exact name match
sub-auto=fuzzy

# Allow ASS subtitles to specify their own formatting. This is default for
# the primary one, but the secondary defaults to strip. Thus this may have
# unforeseen issues used together, but I guess toggling subtitles by j would
# fix it.
sub-ass-override=yes
secondary-sub-ass-override=yes

# Use decreased volume by default so when Mumbling or other VoIP mpv is
# quieter than other people. 70 may be better while VoIPing, but 80 is
# comfortable watching alone and / and * always exist.
volume=80

# Fullscreen by default
#fs=yes
# Windows maximized by default
window-maximized=yes
