# Source: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#unsandboxed-applications
#L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0
L %t/app/com.discordapp.Discord/discord-ipc-0 - - - - snap.discord/discord-ipc-0
L %t/discord-ipc-0 - - - - snap.discord/discord-ipc-0

# After this file is created
# systemctl --user enable --now systemd-tmpfiles-setup.service
