# flatpak & snap & co.
. /etc/profile
# Using dbus-launch seems to be necessary here to get dbus up, otherwise
# there are errors about it missing and pasystray & nm-applet cannot be
# interacted with.
exec dbus-launch --exit-with-session i3
