[Service]
# The overlayfs is not BTRFS and errors out, so the actual partition needs
# to be specified.
ExecStartPre=-btrfs balance cancel /var/home
ExecStart=btrfs balance start --full-balance /var/home
