# Quad9 only. Vulnerable to rare cases when Quad9 is down. ECS so individual
# spying possible. Maybe mitigated by expired stale serving and higher TTL?
# 443 commented in case mobile configuration or backup desired even without
# ECS or domain filtering.
server:
	# Debian ca-certificates location
	#tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
	# Fedora
	#tls-cert-bundle: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
	# Use system certificates no matter where they are
	tls-system-cert: yes
	# Quad9 says pointless performance impact on forwarders.
	# https://docs.quad9.net/Quad9_For_Organizations/DNS_Forwarder_Best_Practices/#disable-qname-minimization
	qname-minimisation: no

forward-zone:
	name: "."
	forward-tls-upstream: yes
	# Quad9 Secure + ECS
	forward-host: dns11.quad9.net@853#dns11.quad9.net
	forward-host: dns11.quad9.net@8853#dns11.quad9.net
	forward-addr: 2620:fe::fe:11@853#dns11.quad9.net
	forward-addr: 2620:fe::fe:11@8853#dns11.quad9.net
	forward-addr: 9.9.9.11@853#dns11.quad9.net
	forward-addr: 9.9.9.11@8853#dns11.quad9.net
	forward-addr: 2620:fe::11@853#dns11.quad9.net
	forward-addr: 2620:fe::11@8853#dns11.quad9.net
	forward-addr: 149.112.112.11@853#dns11.quad9.net
	forward-addr: 149.112.112.11@8853#dns11.quad9.net

	# https://appliedprivacy.net/services/dns/ - Vienna, Austria, no ECS
	#forward-host: dot1.applied-privacy.net@443#dot1.applied-privacy.net
	#forward-addr: 2a02:1b8:10:234::2@443#dot1.applied-privacy.net
	#forward-addr: 146.255.56.98@443#dot1.applied-privacy.net
# vim: filetype=unbound.conf
