# This may be required if binding on specific IP address while systemd
# WantedBy=network-online.target instead of After=network-online.target
server:
# Allow binding to any IP address regardless of existence
ip-freebind: yes
