server:
	# Increases TTL of all queries to 2400 seconds (40 minutes) if upstream
	# has a lower one.
	# https://blog.apnic.net/2019/11/12/stop-using-ridiculously-low-dns-ttls/
	# suggests 40 minutes may be sweet spot for also having maximum cache hits
	# and privacy, however it predates RFC 8767 which again only hits in
	# when the authoritative nameserver won't answer in time and has no
	# privacy impact, which is a consideration due to ECS. I used hour for
	# years, but in September 2026 I started questioning myself on that due
	# to captive portals and all that are a corner case scenario and likely
	# broken by DNSSEC validation anyway.
	cache-min-ttl: 2400
	# Also print statistics then
	statistics-interval: 2400

# vim: filetype=unbound.conf
