# Create symlink /etc/pki/tls/cert.pem pointing to /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
# Fedora 44 deprecated that, but some packages (Steam) have trouble if the file doesn't exist
L /etc/pki/tls/cert.pem - - - - /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

