# -*- conf -*-

font=Comic Shanns Mono-Regular:size=10,Noto Sans Mono:size=10, Noto Color Emoji
dpi-aware=yes

#[environment]
#name=value

[cursor]
color=282a36 ffffff

[colors]
foreground=ffffff
background=000000

[tweak]
render-timer=osd
