# -*- conf -*-

font=Atkinson Hyperlegible Mono:size=10,Ubuntu Sans Mono:size=10,Comic Shanns Mono-Regular:size=10,Noto Sans Mono:size=10, Noto Color Emoji
dpi-aware=yes

[colors-light]
alpha=0.7
background=ffffff
cursor=282a36 000000
foreground=000000

[colors-dark]
alpha=0.7
background=000000
cursor=282a36 ffffff
foreground=ffffff

[environment]
COLORTERM=truecolor
TERM=foot
MANGOHUD=1
#PULSE_LATENCY_MSEC=120

#[tweak]
#render-timer=osd
