# Disable automatic suspending and enable HID reset command on connection.
# You will want Bluetooth autosuspend if your Bluetooth adapter turns off
# by itself and Bluetooth devices won't connect without reboot. The resetting
# may be required by some Bluetooth controllers.
options btusb enable_autosuspend=0 reset=1
