# iwd is replacement for wpa_supplicant by Intel

# Important!
# systemctl disable --now wpa_supplicant
# systemctl mask wpa_supplicant
# systemctl restart NetworkManager
# Maybe also [Unit] {Wants,Requires}=iwd.service in NetworkManager.service.d/

[device]
wifi.backend=iwd
wifi.iwd.autoconnect=true
# vim: filetype=NetworkManager.conf
