[main]
# Send data to systemd-resolved
dns=systemd-resolved
rc-manager=auto
# Implied, but made explicit
systemd-resolved=true
# Tell it to use DoT
[connetion]
connection.dns-over-tls=true
# vim: filetype=NetworkManager.conf
